#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

# Kill all processes running /opt/vscode/node
echo "## Killing all processes running /opt/vscode/node"
pkill -f "/opt/vscode/node"

uninstall_xdebug() {
    local version=$1
    local version_underscore=${version//./_}

    echo "## Stop and disable the PHP ${version} Xdebug"
    systemctl stop php${version}xdbg-fpm
    systemctl disable php${version}xdbg-fpm

    echo "## Remove service files"
    rm -rf /etc/init.d/php${version}xdbg-fpm
    rm -rf /lib/systemd/system/php${version}xdbg-fpm.service

    echo "## Uninstall Xdebug for PHP $version"
    apt-get -qq remove php${version}-xdebug

    echo "## Remove Xdebug profile for PHP $version"
    rm -rf /etc/php/${version}xdbg

    echo "## Remove template file"
    rm -rf /usr/local/hestia/data/templates/web/php-fpm/PHP-${version_underscore}xdbg.tpl

}
uninstall_xdebug 7.4
uninstall_xdebug 8.0
uninstall_xdebug 8.1
uninstall_xdebug 8.2
uninstall_xdebug 8.3

# Clean up all vscode- user domains
rm -rf /etc/nginx/conf.d/domains/vscode-*
rm -rf /opt/vscode

if [ -d "/etc/php.pre-xdebug" ]; then
    rm -rf /etc/php.pre-xdebug
fi;

# Restart the services
echo "## Reload systemd manager configuration"
systemctl daemon-reload
echo "## Restarting the Nginx service"
systemctl restart nginx
